version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: livekit_mvp_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    # Enable GPU support if available (falls back gracefully if no GPU)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # CPU-only version for systems without GPU
  ollama-cpu:
    image: ollama/ollama:latest
    container_name: livekit_mvp_ollama_cpu
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    profiles:
      - cpu
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  ollama_data:
    driver: local

# Default profile (tries GPU first, falls back to CPU)
# To explicitly use CPU: docker compose --profile cpu up -d
# To explicitly use GPU: docker compose --profile gpu up -d