# Example settings for LiveKit MVP Agent
# Copy this to settings.toml and customize as needed

[audio]
sample_rate = 16000
channels = 1
chunk_size = 1024
buffer_size = 4096

[stt]
model = "medium"
device = "auto"  # "auto", "cpu", "cuda"
compute_type = "int8"  # "int8", "int16", "float16", "float32"
language = "auto"  # "auto", "en", "fr"
vad_filter = true
vad_threshold = 0.5

[llm]
base_url = "http://localhost:11434"
model = "llama3.1:8b-instruct-q4_K_M"
fallback_model = "mistral:7b-instruct-q4_K_M"
temperature = 0.7
max_tokens = 512
timeout = 30.0

[tts]
primary = "kokoro"  # "kokoro", "piper", "noop"
fallback = "piper"
voice = "en-US-kokoro"
speed = 1.0
quality = "medium"

[vad]
threshold = 0.5
min_silence_duration = 0.5
speech_pad = 0.2
frame_size = 512

[livekit]
url = "ws://localhost:7880"
room_name = "voice-agent-room"
participant_name = "VoiceAgent"
auto_subscribe = true
auto_publish = true

[logging]
level = "INFO"  # "DEBUG", "INFO", "WARNING", "ERROR"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
file = "logs/agent.log"
max_bytes = 10485760  # 10MB
backup_count = 5

[system]
max_concurrent_requests = 5
request_timeout = 30.0
retry_attempts = 3
retry_delay = 1.0

[performance]
use_gpu = true  # Enable GPU acceleration if available
max_memory_usage = "2GB"
prefetch_models = true
cache_size = 1000